### PR TITLE
feat: Ensure to use unwrapped versions of `setTimeout` / `clearTimeout`

### PR DESCRIPTION
**Pull request by mydea**
Let's see if that helps with Angular performance some more...!

Closes https://github.com/getsentry/sentry-javascript/issues/11661 (hopefully...)

### CODE REVIEW

**Review by Lms24 — APPROVED** [review]
Very interesting! It kinda makes sense after thinking about it. ZoneJS patches all of these global APIs so let's see 🍿

**Comment by mydea** [comment]
> Very interesting! It kinda makes sense after thinking about it. ZoneJS patches all of these global APIs so let's see 🍿
> 
> (long term this might phase out with Angular becoming zone-less in favor of signals but this will take a long time until it's used broadly)

Yeah, I'd say the bundle size hit is acceptable here, and we can revert it later if we want/need to!

**Review by billyvg — APPROVED** [review]
🙏 

We will also want to do this for the setTimeouts in our replay package

**Comment by billyvg** [comment]
> > 🙏
> > We will also want to do this for the setTimeouts in our replay package
> 
> Let's ship this, I'd say, and see if it already improves things, than we can also add this to replay itself, at least in hot paths related to rrweb events etc!

@mydea when I was debugging, I saw that it was being triggered by our click handler in the replay package

**Comment by mydea** [comment]
> > > 🙏
> > > We will also want to do this for the setTimeouts in our replay package
> > 
> > 
> > Let's ship this, I'd say, and see if it already improves things, than we can also add this to replay itself, at least in hot paths related to rrweb events etc!
> 
> @mydea when I was debugging, I saw that it was being triggered by our click handler in the replay package

sad! I guess let's implement it there as well then, will add some bundle size but I guess it's worth it!

**Pull request merged**
